name: Bot
run-name: 🤖 beep boop
on:
  issue_comment:
    types:
      - created
jobs:
  bot:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ./.github/actions/bot
        with:
          ref: ${{ github.event.pull_request.head.sha }}
