name: "[CI] Auto"
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    - run: go install mvdan.cc/sh/v3/cmd/shfmt@latest
    - run: make lint
  templates-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make test
  nodeadm-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cd nodeadm && make build
  nodeadm-check-generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: hack/nodeadm-check-generate.sh
  nodeadm-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cd nodeadm && make test
  nodeadm-test-e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cd nodeadm && make test-e2e
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/dependency-review-action@v4
  gosec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: securego/gosec@master
        with:
          args: -exclude=G101,G103,G204 nodeadm/...
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.21.6
          work-dir: ./nodeadm
          go-version-file: nodeadm/go.mod
          cache: false
          repo-checkout: false