name: "Dependency Review"
on:
  pull_request:
    branches:
      - "master"
      - "al2023"
permissions:
  contents: read
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          show-progress: false
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v4
  gosec:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: nodeadm/...
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          show-progress: false
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.21.6
          work-dir: ./nodeadm
          go-version-file: nodeadm/go.mod
          cache: false
          repo-checkout: false