#!/bin/sh

echo -n "
#############################################################
By using the EKS GPU Optimized AMI, you agree to Nvidia’s End
User License Agreement
https://www.nvidia.com/en-us/about-nvidia/eula-agreement/.
#############################################################
"